# Analise data/database.db

Aqui consta a análise prévia do nosso banco de dados criado. Agora, o objetivo principal é listar o título do projeto e a descrição do projeto

In [13]:
import sqlite3 
import pandas as pd

In [14]:
# Conectar ao banco
conn = sqlite3.connect("/home/darkcover/Documentos/Workana/data/workana.db")

# Criar cursor
cursor = conn.cursor()

# Ver tabelas do banco
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

df = pd.read_sql("SELECT * FROM projetos", conn)
print(df.head())

[('projetos',), ('sqlite_sequence',)]
   id                                               hash  \
0   1  e39ee929380b74e42a1e008c5fb04c743c4fcaac7b4048...
1   2  4c322b1539803203446ce550a9e9f22400b56483dbcd35...
2   3  5c646b554323ac992d640ea8c6d45739ba76c95b531497...
3   4  829ff224dfd2dd0f349e690c472f5ef426f3ffbce89d19...
4   5  3314120e731903a4fe98db0f1cef897131d1caa444b0c1...

                                              titulo  \
0  Desenvolvimento de Agente de Ia para Atendimen...
1  Desenvolvimento de Solução de Proteção Intelig...
2  Desenvolvimento de Múltiplos Agentes de Ia par...
3  Desenvolvimento de Chatbot com Ia para Automaç...
4  Arquiteto e Desenvolvedor Python Sênior para I...

                                                link  \
0  https://www.workana.com/job/desenvolvimento-de...
1  https://www.workana.com/job/desenvolvimento-de...
2  https://www.workana.com/job/desenvolvimento-de...
3  https://www.workana.com/job/desenvolvimento-de...
4  https://www.workana.com/job/arquiteto-e-desenv...

                                           descricao  cliente_verificado  \
0  Encontre trabalho\nMeus projetos\nMinhas finan...                   0
1  Encontre trabalho\nMeus projetos\nMinhas finan...                   0
2  Encontre trabalho\nMeus projetos\nMinhas finan...                   0
3  Encontre trabalho\nMeus projetos\nMinhas finan...                   0
4  Encontre trabalho\nMeus projetos\nMinhas finan...                   0

   cliente_pagamento_verificado  \
0                             0
1                             0
2                             0
3                             0
4                             0

                                   cliente_historico  enviar_proposta  \
0                                                                   0
1                                                                   0
2  Outro projetos publicados por Gabriel D. S. M. B.                0
3                                                                   0
4               Outro projetos publicados por Felipe                0

   enviado_telegram          data_coleta
0                 0  2026-03-29 04:16:33
1                 0  2026-03-29 04:16:38
2                 0  2026-03-29 04:16:44
3                 0  2026-03-29 04:16:49
4                 0  2026-03-29 04:16:54

In [15]:
df.head()

,id,hash,titulo,link,descricao,cliente_verificado,cliente_pagamento_verificado,cliente_historico,enviar_proposta,enviado_telegram,data_coleta
0,1,e39ee929380b74e42a1e008c5fb04c743c4fcaac7b4048...,Desenvolvimento de Agente de Ia para Atendimen...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,,0,0,2026-03-29 04:16:33
1,2,4c322b1539803203446ce550a9e9f22400b56483dbcd35...,Desenvolvimento de Solução de Proteção Intelig...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,,0,0,2026-03-29 04:16:38
2,3,5c646b554323ac992d640ea8c6d45739ba76c95b531497...,Desenvolvimento de Múltiplos Agentes de Ia par...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Gabriel D. S. M. B.,0,0,2026-03-29 04:16:44
3,4,829ff224dfd2dd0f349e690c472f5ef426f3ffbce89d19...,Desenvolvimento de Chatbot com Ia para Automaç...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,,0,0,2026-03-29 04:16:49
4,5,3314120e731903a4fe98db0f1cef897131d1caa444b0c1...,Arquiteto e Desenvolvedor Python Sênior para I...,https://www.workana.com/job/arquiteto-e-desenv...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Felipe,0,0,2026-03-29 04:16:54

In [16]:
df.describe()

,id,cliente_verificado,cliente_pagamento_verificado,enviar_proposta,enviado_telegram
count,20.00000,20.0,20.0,20.0,20.0
mean,10.50000,0.0,0.0,0.0,0.0
std,5.91608,0.0,0.0,0.0,0.0
min,1.00000,0.0,0.0,0.0,0.0
25%,5.75000,0.0,0.0,0.0,0.0
50%,10.50000,0.0,0.0,0.0,0.0
75%,15.25000,0.0,0.0,0.0,0.0
max,20.00000,0.0,0.0,0.0,0.0

In [17]:
df.columns

Index(['id', 'hash', 'titulo', 'link', 'descricao', 'cliente_verificado',
       'cliente_pagamento_verificado', 'cliente_historico', 'enviar_proposta',
       'enviado_telegram', 'data_coleta'],
      dtype='str')

## Explicação das colunas
Documento do banco de dados base no `database.py`.

---

### Tabela: `projetos`

Essa tabela armazena todos os projetos coletados do Workana.

| Coluna                         | Tipo          | Descrição                                           |
| ------------------------------ | ------------- | --------------------------------------------------- |
| `id`                           | INTEGER       | Identificador único do projeto no banco             |
| `hash`                         | TEXT (UNIQUE) | Hash único do projeto para evitar duplicação        |
| `titulo`                       | TEXT          | Título do projeto no Workana                        |
| `link`                         | TEXT (UNIQUE) | Link do projeto no Workana                          |
| `descricao`                    | TEXT          | Descrição completa do projeto                       |
| `cliente_verificado`           | BOOLEAN       | Indica se o cliente é verificado                    |
| `cliente_pagamento_verificado` | BOOLEAN       | Indica se o cliente tem pagamento verificado        |
| `cliente_historico`            | TEXT          | Histórico do cliente (ex: "10 projetos publicados") |
| `enviar_proposta`              | BOOLEAN       | Indica se esse projeto deve receber proposta        |
| `enviado_telegram`             | BOOLEAN       | Indica se o projeto já foi enviado ao Telegram      |
| `data_coleta`                  | TIMESTAMP     | Data e hora que o projeto foi coletado              |

---

In [18]:
type(df)

pandas.DataFrame

In [19]:
# Criar o filtro: 
# 1. cliente_pagamento_verificado diferente de 0 (ou seja, é 1) [cite: 133, 149]
# 2. OU cliente_historico não é uma string vazia [cite: 134, 149]
filtro_valido = (df['cliente_pagamento_verificado'] != 0) | (df['cliente_historico'] != '')

# Aplicar o filtro ao DataFrame original para manter todas as colunas [cite: 109, 110, 111]
df_final = df[filtro_valido].reset_index(drop=True)

In [20]:
df_final.head()

,id,hash,titulo,link,descricao,cliente_verificado,cliente_pagamento_verificado,cliente_historico,enviar_proposta,enviado_telegram,data_coleta
0,3,5c646b554323ac992d640ea8c6d45739ba76c95b531497...,Desenvolvimento de Múltiplos Agentes de Ia par...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Gabriel D. S. M. B.,0,0,2026-03-29 04:16:44
1,5,3314120e731903a4fe98db0f1cef897131d1caa444b0c1...,Arquiteto e Desenvolvedor Python Sênior para I...,https://www.workana.com/job/arquiteto-e-desenv...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Felipe,0,0,2026-03-29 04:16:54
2,10,fce94f97ba34fb06073ea4aec5e119115ad3aabfab89ec...,Desenvolvimento e Integração de Ia para Respos...,https://www.workana.com/job/desenvolvimento-e-...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Ana P.,0,0,2026-03-29 04:17:20
3,11,e00ab0e246f65e5d8f66799fb18e4d333633d26306c66f...,Desenvolvimento de Sistema de Automação de Res...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Ana P.,0,0,2026-03-29 04:17:25
4,13,b889ad7a5dbf650b997ed32e393bb55ea6111baf84b2b7...,Desenvolvimento de Gerador de Sinais Preditivo...,https://www.workana.com/job/desenvolvimento-de...,Encontre trabalho\nMeus projetos\nMinhas finan...,0,0,Outro projetos publicados por Sndndn,0,0,2026-03-29 04:17:34

In [21]:
conn.close()

## Analise da última linha

In [22]:
def limpar_descricao(texto):
    # O conteúdo real geralmente começa após "Sobre este projeto" 
    # e termina antes de "Categoria"
    try:
        inicio = texto.split("Sobre este projeto")[1]
        fim = inicio.split("Freelancers interessados")[0]
        return fim.strip()
    except:
        return texto # Caso não encontre o padrão, mantém o original

dfLinhaTeste = limpar_descricao(df_final.iloc[-1]['descricao'])
print(dfLinhaTeste)

R$ 110 - 240 / hora
Estamos buscando um especialista para a implantação de uma solução de Business Intelligence utilizando Power BI para uma rede de clínicas. O projeto envolve a integração e análise de dados de diversas áreas, incluindo financeiro, operacional e comercial. O objetivo é criar dashboards e relatórios interativos que forneçam insights claros e acionáveis para a tomada de decisões estratégicas.

As principais responsabilidades incluem:

1.  Levantamento de requisitos detalhados com as equipes de finanças, operações e comercial.
2.  Conexão e extração de dados de diferentes fontes (sistemas de gestão, planilhas, bancos de dados).
3.  Modelagem e transformação de dados para garantir a integridade e usabilidade.
4.  Desenvolvimento de dashboards e relatórios personalizados no Power BI.
5.  Criação de indicadores chave de desempenho (KPIs) para cada área.
6.  Treinamento das equipes internas para utilização da ferramenta.
7.  Manutenção e otimização inicial da solução.

Esperamos um profissional com experiência comprovada em projetos de Power BI, forte capacidade analítica e habilidade para comunicar resultados complexos de forma clara. O projeto visa otimizar a gestão e performance da rede de clínicas através de uma visão unificada e em tempo real dos dados.
Categoria TI e Programação
Subcategoria Data Science
Tamanho do projeto Grande
Duração do projeto Não estabelecido
Habilidades necessárias
Power BI
Fazer uma proposta Faça uma pergunta
Mateus B.
11
Projetos publicados
7
Projetos pagos
Membro desde: Março 2019
Atividades neste projeto
24
Propostas
28

## Organização da blbioteca para o telegram

Aqui está um estudo básico sobre a biblioteca 

```text
python-telegram-bot
```

É necessário saber o uso do botfather e uso de tokens gerados pelo botfather, o daqui, foi oculto dentro do arquivo .env

In [23]:
import os
from dotenv import load_dotenv
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
from telegram import Update
import asyncio

In [24]:
# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

True

In [25]:
TOKEN = os.getenv("TELEGRAM_TOKEN")